<?php
	$emotionListDefault = array(
		array(
			'groupname' => __('哔哩哔哩', 'argon'), 
			'list' => array(
				array('type' => 'sm_sticker', 'code' => '[脱单doge]', 'src' => $GLOBALS['assets_path'] . '/stickers/bilibili/1.png'),
				array('type' => 'sm_sticker', 'code' => '[微笑]', 'src' => $GLOBALS['assets_path'] . '/stickers/bilibili/2.png'),
				array('type' => 'sm_sticker', 'code' => '[口罩]', 'src' => $GLOBALS['assets_path'] . '/stickers/bilibili/3.png'),
				array('type' => 'sm_sticker', 'code' => '[doge]', 'src' => $GLOBALS['assets_path'] . '/stickers/bilibili/4.png'),
				array('type' => 'sm_sticker', 'code' => '[妙啊]', 'src' => $GLOBALS['assets_path'] . '/stickers/bilibili/5.png'),
				array('type' => 'sm_sticker', 'code' => '[藏狐]', 'src' => $GLOBALS['assets_path'] . '/stickers/bilibili/6.png'),
				array('type' => 'sm_sticker', 'code' => '[OK]', 'src' => $GLOBALS['assets_path'] . '/stickers/bilibili/7.png'),
				array('type' => 'sm_sticker', 'code' => '[星星眼]', 'src' => $GLOBALS['assets_path'] . '/stickers/bilibili/8.png'),
				array('type' => 'sm_sticker', 'code' => '[辣眼睛]', 'src' => $GLOBALS['assets_path'] . '/stickers/bilibili/9.png'),
				array('type' => 'sm_sticker', 'code' => '[吃瓜]', 'src' => $GLOBALS['assets_path'] . '/stickers/bilibili/10.png'),
				array('type' => 'sm_sticker', 'code' => '[滑稽]', 'src' => $GLOBALS['assets_path'] . '/stickers/bilibili/11.png'),
				array('type' => 'sm_sticker', 'code' => '[呲牙]', 'src' => $GLOBALS['assets_path'] . '/stickers/bilibili/12.png'),
				array('type' => 'sm_sticker', 'code' => '[歪嘴]', 'src' => $GLOBALS['assets_path'] . '/stickers/bilibili/13.png'),
				array('type' => 'sm_sticker', 'code' => '[打call]', 'src' => $GLOBALS['assets_path'] . '/stickers/bilibili/14.png'),
				array('type' => 'sm_sticker', 'code' => '[嗑瓜子]', 'src' => $GLOBALS['assets_path'] . '/stickers/bilibili/15.png'),
				array('type' => 'sm_sticker', 'code' => '[笑哭]', 'src' => $GLOBALS['assets_path'] . '/stickers/bilibili/16.png'),
				array('type' => 'sm_sticker', 'code' => '[脸红]', 'src' => $GLOBALS['assets_path'] . '/stickers/bilibili/17.png'),
				array('type' => 'sm_sticker', 'code' => '[给心心]', 'src' => $GLOBALS['assets_path'] . '/stickers/bilibili/18.png'),
				array('type' => 'sm_sticker', 'code' => '[嘟嘟]', 'src' => $GLOBALS['assets_path'] . '/stickers/bilibili/19.png'),
				array('type' => 'sm_sticker', 'code' => '[哦呼]', 'src' => $GLOBALS['assets_path'] . '/stickers/bilibili/20.png'),
				array('type' => 'sm_sticker', 'code' => '[喜欢]', 'src' => $GLOBALS['assets_path'] . '/stickers/bilibili/21.png'),
				array('type' => 'sm_sticker', 'code' => '[酸了]', 'src' => $GLOBALS['assets_path'] . '/stickers/bilibili/22.png'),
				array('type' => 'sm_sticker', 'code' => '[嫌弃]', 'src' => $GLOBALS['assets_path'] . '/stickers/bilibili/23.png'),
				array('type' => 'sm_sticker', 'code' => '[害羞]', 'src' => $GLOBALS['assets_path'] . '/stickers/bilibili/24.png'),
				array('type' => 'sm_sticker', 'code' => '[豹富]', 'src' => $GLOBALS['assets_path'] . '/stickers/bilibili/25.png'),
				array('type' => 'sm_sticker', 'code' => '[大哭]', 'src' => $GLOBALS['assets_path'] . '/stickers/bilibili/26.png'),
				array('type' => 'sm_sticker', 'code' => '[疑惑]', 'src' => $GLOBALS['assets_path'] . '/stickers/bilibili/27.png'),
				array('type' => 'sm_sticker', 'code' => '[喜极而泣]', 'src' => $GLOBALS['assets_path'] . '/stickers/bilibili/28.png'),
				array('type' => 'sm_sticker', 'code' => '[笑]', 'src' => $GLOBALS['assets_path'] . '/stickers/bilibili/29.png'),
				array('type' => 'sm_sticker', 'code' => '[偷笑]', 'src' => $GLOBALS['assets_path'] . '/stickers/bilibili/30.png'),
				array('type' => 'sm_sticker', 'code' => '[惊讶]', 'src' => $GLOBALS['assets_path'] . '/stickers/bilibili/31.png'),
				array('type' => 'sm_sticker', 'code' => '[囧]', 'src' => $GLOBALS['assets_path'] . '/stickers/bilibili/32.png'),
				array('type' => 'sm_sticker', 'code' => '[呆]', 'src' => $GLOBALS['assets_path'] . '/stickers/bilibili/33.png'),
				array('type' => 'sm_sticker', 'code' => '[抠鼻]', 'src' => $GLOBALS['assets_path'] . '/stickers/bilibili/34.png'),
				array('type' => 'sm_sticker', 'code' => '[大笑]', 'src' => $GLOBALS['assets_path'] . '/stickers/bilibili/35.png'),
				array('type' => 'sm_sticker', 'code' => '[惊喜]', 'src' => $GLOBALS['assets_path'] . '/stickers/bilibili/36.png'),
				array('type' => 'sm_sticker', 'code' => '[无语]', 'src' => $GLOBALS['assets_path'] . '/stickers/bilibili/37.png'),
				array('type' => 'sm_sticker', 'code' => '[点赞]', 'src' => $GLOBALS['assets_path'] . '/stickers/bilibili/38.png'),
				array('type' => 'sm_sticker', 'code' => '[鼓掌]', 'src' => $GLOBALS['assets_path'] . '/stickers/bilibili/39.png'),
				array('type' => 'sm_sticker', 'code' => '[尴尬]', 'src' => $GLOBALS['assets_path'] . '/stickers/bilibili/40.png'),
				array('type' => 'sm_sticker', 'code' => '[灵魂出窍]', 'src' => $GLOBALS['assets_path'] . '/stickers/bilibili/41.png'),
				array('type' => 'sm_sticker', 'code' => '[委屈]', 'src' => $GLOBALS['assets_path'] . '/stickers/bilibili/42.png'),
				array('type' => 'sm_sticker', 'code' => '[疼]', 'src' => $GLOBALS['assets_path'] . '/stickers/bilibili/43.png'),
				array('type' => 'sm_sticker', 'code' => '[冷]', 'src' => $GLOBALS['assets_path'] . '/stickers/bilibili/44.png'),
				array('type' => 'sm_sticker', 'code' => '[热]', 'src' => $GLOBALS['assets_path'] . '/stickers/bilibili/45.png'),
				array('type' => 'sm_sticker', 'code' => '[生病]', 'src' => $GLOBALS['assets_path'] . '/stickers/bilibili/46.png'),
				array('type' => 'sm_sticker', 'code' => '[捂眼]', 'src' => $GLOBALS['assets_path'] . '/stickers/bilibili/47.png'),
				array('type' => 'sm_sticker', 'code' => '[思考]', 'src' => $GLOBALS['assets_path'] . '/stickers/bilibili/48.png'),
				array('type' => 'sm_sticker', 'code' => '[再见]', 'src' => $GLOBALS['assets_path'] . '/stickers/bilibili/49.png'),
				array('type' => 'sm_sticker', 'code' => '[抓狂]', 'src' => $GLOBALS['assets_path'] . '/stickers/bilibili/50.png'),
				array('type' => 'sm_sticker', 'code' => '[翻白眼]', 'src' => $GLOBALS['assets_path'] . '/stickers/bilibili/51.png'),
				array('type' => 'sm_sticker', 'code' => '[哈欠]', 'src' => $GLOBALS['assets_path'] . '/stickers/bilibili/52.png'),
				array('type' => 'sm_sticker', 'code' => '[奋斗]', 'src' => $GLOBALS['assets_path'] . '/stickers/bilibili/53.png'),
				array('type' => 'sm_sticker', 'code' => '[墨镜]', 'src' => $GLOBALS['assets_path'] . '/stickers/bilibili/54.png'),
				array('type' => 'sm_sticker', 'code' => '[撇嘴]', 'src' => $GLOBALS['assets_path'] . '/stickers/bilibili/55.png'),
				array('type' => 'sm_sticker', 'code' => '[难过]', 'src' => $GLOBALS['assets_path'] . '/stickers/bilibili/56.png'),
				array('type' => 'sm_sticker', 'code' => '[生气]', 'src' => $GLOBALS['assets_path'] . '/stickers/bilibili/57.png'),
				array('type' => 'sm_sticker', 'code' => '[爱心]', 'src' => $GLOBALS['assets_path'] . '/stickers/bilibili/58.png'),
				array('type' => 'sm_sticker', 'code' => '[保卫萝卜_白眼]', 'src' => $GLOBALS['assets_path'] . '/stickers/bilibili/59.png'),
				array('type' => 'sm_sticker', 'code' => '[保卫萝卜_笔芯]', 'src' => $GLOBALS['assets_path'] . '/stickers/bilibili/60.png'),
				array('type' => 'sm_sticker', 'code' => '[保卫萝卜_哭哭]', 'src' => $GLOBALS['assets_path'] . '/stickers/bilibili/61.png'),
				array('type' => 'sm_sticker', 'code' => '[保卫萝卜_哇]', 'src' => $GLOBALS['assets_path'] . '/stickers/bilibili/62.png'),
				array('type' => 'sm_sticker', 'code' => '[保卫萝卜_问号]', 'src' => $GLOBALS['assets_path'] . '/stickers/bilibili/63.png'),
				array('type' => 'sm_sticker', 'code' => '[保佑]', 'src' => $GLOBALS['assets_path'] . '/stickers/bilibili/64.png'),
				array('type' => 'sm_sticker', 'code' => '[抱拳]', 'src' => $GLOBALS['assets_path'] . '/stickers/bilibili/65.png'),
				array('type' => 'sm_sticker', 'code' => '[加油]', 'src' => $GLOBALS['assets_path'] . '/stickers/bilibili/66.png'),
				array('type' => 'sm_sticker', 'code' => '[胜利]', 'src' => $GLOBALS['assets_path'] . '/stickers/bilibili/67.png'),
				array('type' => 'sm_sticker', 'code' => '[响指]', 'src' => $GLOBALS['assets_path'] . '/stickers/bilibili/68.png'),
				array('type' => 'sm_sticker', 'code' => '[支持]', 'src' => $GLOBALS['assets_path'] . '/stickers/bilibili/69.png'),
				array('type' => 'sm_sticker', 'code' => '[拥抱]', 'src' => $GLOBALS['assets_path'] . '/stickers/bilibili/70.png'),
				array('type' => 'sm_sticker', 'code' => '[怪我咯]', 'src' => $GLOBALS['assets_path'] . '/stickers/bilibili/71.png'),
				array('type' => 'sm_sticker', 'code' => '[跪了]', 'src' => $GLOBALS['assets_path'] . '/stickers/bilibili/72.png'),
				array('type' => 'sm_sticker', 'code' => '[鸡腿]', 'src' => $GLOBALS['assets_path'] . '/stickers/bilibili/73.png'),
				array('type' => 'sm_sticker', 'code' => '[奶茶干杯]', 'src' => $GLOBALS['assets_path'] . '/stickers/bilibili/74.png'),
				array('type' => 'sm_sticker', 'code' => '[福到了]', 'src' => $GLOBALS['assets_path'] . '/stickers/bilibili/75.png'),
			)
		),
		array(
			'groupname' => __('颜文字', 'argon'), 
			'list' => array(
				array('type' => 'text', 'text' => "|´・ω・)ノ"),
				array('type' => 'text', 'text' => "ヾ(≧∇≦*)ゝ"),
				array('type' => 'text', 'text' => "(☆ω☆)"),
				array('type' => 'text', 'text' => "（╯‵□′）╯︵┴─┴"),
				array('type' => 'text', 'text' => "￣﹃￣"),
				array('type' => 'text', 'text' => "(/ω＼)"),
				array('type' => 'text', 'text' => "∠( ᐛ 」∠)＿"),
				array('type' => 'text', 'text' => "(๑•̀ㅁ•́ฅ)"),
				array('type' => 'text', 'text' => "→_→"),
				array('type' => 'text', 'text' => "୧(๑•̀⌄•́๑)૭"),
				array('type' => 'text', 'text' => "٩(ˊᗜˋ*)و"),
				array('type' => 'text', 'text' => "(ノ°ο°)ノ"),
				array('type' => 'text', 'text' => "(´இ皿இ｀)"),
				array('type' => 'text', 'text' => "⌇●﹏●⌇"),
				array('type' => 'text', 'text' => "(ฅ´ω`ฅ)"),
				array('type' => 'text', 'text' => "(╯°A°)╯︵○○○"),
				array('type' => 'text', 'text' => "φ(￣∇￣o)"),
				array('type' => 'text', 'text' => "ヾ(´･ ･｀｡)ノ\""),
				array('type' => 'text', 'text' => "( ง ᵒ̌皿ᵒ̌)ง⁼³₌₃"),
				array('type' => 'text', 'text' => "(ó﹏ò｡)"),
				array('type' => 'text', 'text' => "Σ(っ °Д °;)っ"),
				array('type' => 'text', 'text' => "( ,,´･ω･)ﾉ\"(´っω･｀｡)"),
				array('type' => 'text', 'text' => "╮(╯▽╰)╭"),
				array('type' => 'text', 'text' => "o(*////▽////*)q"),
				array('type' => 'text', 'text' => "＞﹏＜"),
				array('type' => 'text', 'text' => "( ๑´•ω•) \"(ㆆᴗㆆ)")
			)
		),
		array(
			'groupname' => 'Emoji', 
			'list' => array(
				array('type' => 'text', 'text' => "😂"),
				array('type' => 'text', 'text' => "😀"),
				array('type' => 'text', 'text' => "😅"),
				array('type' => 'text', 'text' => "😊"),
				array('type' => 'text', 'text' => "🙂"),
				array('type' => 'text', 'text' => "🙃"),
				array('type' => 'text', 'text' => "😌"),
				array('type' => 'text', 'text' => "😍"),
				array('type' => 'text', 'text' => "😘"),
				array('type' => 'text', 'text' => "😜"),
				array('type' => 'text', 'text' => "😝"),
				array('type' => 'text', 'text' => "😏"),
				array('type' => 'text', 'text' => "😒"),
				array('type' => 'text', 'text' => "🙄"),
				array('type' => 'text', 'text' => "😳"),
				array('type' => 'text', 'text' => "😡"),
				array('type' => 'text', 'text' => "😔"),
				array('type' => 'text', 'text' => "😫"),
				array('type' => 'text', 'text' => "😱"),
				array('type' => 'text', 'text' => "😭"),
				array('type' => 'text', 'text' => "💩"),
				array('type' => 'text', 'text' => "👻"),
				array('type' => 'text', 'text' => "🙌"),
				array('type' => 'text', 'text' => "🖕"),
				array('type' => 'text', 'text' => "👍"),
				array('type' => 'text', 'text' => "👫"),
				array('type' => 'text', 'text' => "👬"),
				array('type' => 'text', 'text' => "👭"),
				array('type' => 'text', 'text' => "🌚"),
				array('type' => 'text', 'text' => "🌝"),
				array('type' => 'text', 'text' => "🙈"),
				array('type' => 'text', 'text' => "💊"),
				array('type' => 'text', 'text' => "😶"),
				array('type' => 'text', 'text' => "🙏"),
				array('type' => 'text', 'text' => "🍦"),
				array('type' => 'text', 'text' => "🍉"),
				array('type' => 'text', 'text' => "😣")
			)
		),
		array(
			'groupname' => '小恐龙', 
			'list' => array(
				array('type' => 'sticker', 'code' => 'dinosaur-shy', 'src' => $GLOBALS['assets_path'] . '/stickers/dinosaur/1.jpg'),
				array('type' => 'sticker', 'code' => 'dinosaur-daze', 'src' => $GLOBALS['assets_path'] . '/stickers/dinosaur/2.jpg'),
				array('type' => 'sticker', 'code' => 'dinosaur-sweat', 'src' => $GLOBALS['assets_path'] . '/stickers/dinosaur/3.jpg'),
				array('type' => 'sticker', 'code' => 'dinosaur-proud', 'src' => $GLOBALS['assets_path'] . '/stickers/dinosaur/4.jpg'),
				array('type' => 'sticker', 'code' => 'dinosaur-powerless', 'src' => $GLOBALS['assets_path'] . '/stickers/dinosaur/5.jpg'),
				array('type' => 'sticker', 'code' => 'dinosaur-pouting', 'src' => $GLOBALS['assets_path'] . '/stickers/dinosaur/6.jpg'),
				array('type' => 'sticker', 'code' => 'dinosaur-eating', 'src' => $GLOBALS['assets_path'] . '/stickers/dinosaur/7.jpg'),
				array('type' => 'sticker', 'code' => 'dinosaur-ok', 'src' => $GLOBALS['assets_path'] . '/stickers/dinosaur/8.jpg'),
				array('type' => 'sticker', 'code' => 'dinosaur-doubt', 'src' => $GLOBALS['assets_path'] . '/stickers/dinosaur/9.jpg'),
				array('type' => 'sticker', 'code' => 'dinosaur-depressed', 'src' => $GLOBALS['assets_path'] . '/stickers/dinosaur/10.jpg'),
				array('type' => 'sticker', 'code' => 'dinosaur-close-eyes', 'src' => $GLOBALS['assets_path'] . '/stickers/dinosaur/11.jpg'),
				array('type' => 'sticker', 'code' => 'dinosaur-sleeping', 'src' => $GLOBALS['assets_path'] . '/stickers/dinosaur/12.jpg'),
				array('type' => 'sticker', 'code' => 'dinosaur-puzzled', 'src' => $GLOBALS['assets_path'] . '/stickers/dinosaur/13.jpg'),
				array('type' => 'sticker', 'code' => 'dinosaur-agree', 'src' => $GLOBALS['assets_path'] . '/stickers/dinosaur/14.jpg'),
				array('type' => 'sticker', 'code' => 'dinosaur-crazy', 'src' => $GLOBALS['assets_path'] . '/stickers/dinosaur/15.jpg'),
				array('type' => 'sticker', 'code' => 'dinosaur-angry', 'src' => $GLOBALS['assets_path'] . '/stickers/dinosaur/16.jpg')
			)
		),
		array(
			'groupname' => '花!', 
			'list' => array(
				array('type' => 'sticker', 'code' => 'flower-flower', 'src' => $GLOBALS['assets_path'] . '/stickers/flower/1.jpg'),
				array('type' => 'sticker', 'code' => 'flower-grass', 'src' => $GLOBALS['assets_path'] . '/stickers/flower/2.jpg'),
				array('type' => 'sticker', 'code' => 'flower-leaf', 'src' => $GLOBALS['assets_path'] . '/stickers/flower/3.jpg'),
				array('type' => 'sticker', 'code' => 'flower-star', 'src' => $GLOBALS['assets_path'] . '/stickers/flower/4.jpg'),
				array('type' => 'sticker', 'code' => 'flower-sun', 'src' => $GLOBALS['assets_path'] . '/stickers/flower/5.jpg'),
				array('type' => 'sticker', 'code' => 'flower-moon', 'src' => $GLOBALS['assets_path'] . '/stickers/flower/6.jpg'),
				array('type' => 'sticker', 'code' => 'flower-water', 'src' => $GLOBALS['assets_path'] . '/stickers/flower/7.jpg'),
				array('type' => 'sticker', 'code' => 'flower-heihei', 'src' => $GLOBALS['assets_path'] . '/stickers/flower/8.jpg'),
				array('type' => 'sticker', 'code' => 'flower-lemon', 'src' => $GLOBALS['assets_path'] . '/stickers/flower/9.jpg'),
				array('type' => 'sticker', 'code' => 'flower-birthday', 'src' => $GLOBALS['assets_path'] . '/stickers/flower/10.jpg'),
				array('type' => 'sticker', 'code' => 'flower-sea', 'src' => $GLOBALS['assets_path'] . '/stickers/flower/11.jpg'),
				array('type' => 'sticker', 'code' => 'flower-vegetable', 'src' => $GLOBALS['assets_path'] . '/stickers/flower/12.jpg'),
				array('type' => 'sticker', 'code' => 'flower-tile', 'src' => $GLOBALS['assets_path'] . '/stickers/flower/13.jpg'),
				array('type' => 'sticker', 'code' => 'flower-utf', 'src' => $GLOBALS['assets_path'] . '/stickers/flower/14.jpg'),
			),
			'description' => 'Source: github.com/k4yt3x/flowerhd'
		)
	);
?>